### ISSUE TITLE
Problem during execution

### ISSUE THREAD

**Issue by EmanuelCastanho** [daleroberts/s2cloudmask#1]
This is my small script to test s2cloudmask, I don't know if I understood the input right:

```
import rasterio as rio
import matplotlib.pyplot as plt
import s2cloudmask as s2cm

Data = rio.open("data/T26SMH_20181207T124031_TCI_10m.jp2")
DataArray = Data.read(1)
Mask = s2cm.cloud_mask(DataArray, model='spectral')

plt.imshow(Mask)
plt.show()
```

I get these errors:

![Screenshot 2022-02-02 at 17 10 09](https://user-images.githubusercontent.com/69935277/152212872-8e6ebac3-bf27-41c3-95a1-17e2b338eddd.png)

**Comment by DiarmuidMalanaphy** [comment]
you have to install the packages, hdmedians and pcm. 
Depending on your python version you should type 
"pip install pcm" and "pip install hdmedians" or 
"pip3 install pcm" and "pip install hdmedians"
